id: P000775
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18640
  title: རྒྱ་བོད་ཤན་སྦྱར་གྱི་སྐྱེ་དངོས་རིག་པའི་ཚིག་མཛོད།
  author: ''
  volumes:
    ea6b28c22a1c4b5d9a322b4eb3b70a1b:
      image_group_id: I8LS18642
      title: ''
      volume_number: 1
      total_pages: 259
